language: python
cache: pip

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      before_install:
        - pip uninstall -y numpy
    - os: linux
      python: 3.8
    - os: osx
      language: generic
      env:
      - TRAVIS_PYTHON_VERSION=3.6
      - OSX_PKG_ENV=miniconda
    - os: osx
      language: generic
      env:
      - TRAVIS_PYTHON_VERSION=3.7

#    - os: windows
#      language: minimal
#      before_install:
#      - choco install python3 --version 3.7.3
#      - python -m pip install --upgrade pip
#      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
#    - os: windows
#      language: minimal
#      before_install:
#      - choco install python3
#      - python -m pip install --upgrade pip
#      env: PATH="/c/Python38:/c/Python38/Scripts:$PATH"

before_install:
  - python --version
  - pip install -U pip
  - pip install pytest
  - pip install cython
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      source .travis/osx_install.sh;
    else
      source .travis/linux_install.sh;
    fi

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest # run tests
#after_success:
#  - codecov # submit coverage


notifications:
  email: false