language: python
matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7
    - os: osx
      osx_image: xcode11
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.8
    - os: windows
      language: minimal
      before_install:
      - choco install python3
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip uninstall numpy
install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest # run tests
#after_success:
#  - codecov # submit coverage


notifications:
  email: false