language: python
cache: pip

matrix:
  include:
    - os: linux
      python: 3.6
      before_install:
        - pip install -U cython
    - os: linux
      python: 3.7
      before_install:
        - pip uninstall -y numpy
    - os: linux
      python: 3.8
    - os: osx
      osx_image: xcode10.2  # python 3.6.5
      language: shell  # 'language: python' is an error on Travis CI macOS
      env: TRAVIS_PYTHON_VERSION=3.6
    - os: osx
      osx_image: xcode10.2  # python 3.7.3
      language: shell  # 'language: python' is an error on Travis CI macOS
      env: TRAVIS_PYTHON_VERSION=3.7
#    - os: windows
#      language: minimal
#      before_install:
#      - choco install python3 --version 3.7.3
#      - python -m pip install --upgrade pip
#      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
#    - os: windows
#      language: minimal
#      before_install:
#      - choco install python3
#      - python -m pip install --upgrade pip
#      env: PATH="/c/Python38:/c/Python38/Scripts:$PATH"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest # run tests
#after_success:
#  - codecov # submit coverage


notifications:
  email: false